export const ACTIVATEUSER_GETMESSAGECODE = Symbol('ACTIVATEUSER_GETMESSAGECODE') // 获取短信验证码
export const ACTIVATEUSER_GETSTATE = Symbol('ACTIVATEUSER_GETSTATE') // 获取用户状态
export const ACTIVATEUSER_GETUSERINFO = Symbol('ACTIVATEUSER_GETUSERINFO') // 验证是否为UKEY用户
export const ACTIVATEUSER_SAVEACTIVATEINFO = Symbol('ACTIVATEUSER_SAVEACTIVATEINFO') // 保存激活信息
export const ACTIVATEUSER_GETVERIFICATION = Symbol('ACTIVATEUSER_GETVERIFICATION') // 获取验证码
export const ACTIVATEUSER_GETCOMPANYLIST = Symbol('ACTIVATEUSER_GETCOMPANYLIST')   // 获取企业列表