export const COMMON_GETMENULIST = Symbol('COMMON_GETMENULIST')
export const COMMON_GETOPERRULE = Symbol('COMMON_GETOPERRULE')
export const LOGOUT = Symbol('LOGOUT')
export const GETOPERRULEINFO = Symbol('GETOPERRULEINFO')