export const EFTR_GETTABLELIST = 'EFTR_GETTABLELIST'
export const EFTR_GETTABLELISTS = 'EFTR_GETTABLELISTS'
export const EFTR_UPDATESEARCHINFO = 'EFTR_UPDATESEARCHINFO'
export const EFTR_SETCURRENTPAGEONE = 'EFTR_SETCURRENTPAGEONE'
