export const EFEF_GETDATA = 'EFEF_GETDATA'
export const EFEF_GETNUM = 'EFEF_GETNUM'
export const EFEF_ORDERINFO = Symbol('EFEF_ORDERINFO')
export const EFEF_GETLOANINTENTION1 = 'EFEF_GETLOANINTENTION1'
export const EFEF_GETLOGININFO = 'EFEF_GETLOGININFO'
