export const GETLOANINTENTIONLIST = Symbol('GETLOANINTENTIONLIST')
export const LOANINTENTIONSEARCH = Symbol('LOANINTENTIONSEARCH')
export const CLEARLOANINTENTIONSEARCH = Symbol('CLEARLOANINTENTIONSEARCH')