export const GETLOANPROGRESSLIST = Symbol('GETLOANPROGRESSLIST')
export const LOANPROGRESSSEARCH = Symbol('LOANPROGRESSSEARCH')
export const CLEARLOANPROGRESSSEARCH = Symbol('CLEARLOANPROGRESSSEARCH')