export const SMALLREGISTER_GETVERIFICATION = 'SMALLREGISTER_GETVERIFICATION' // 获取图形验证码
export const SMALLREGISTER_GETSMSVERIFICATION = 'SMALLREGISTER_GETSMSVERIFICATION' // 获取短信验证码
export const SMALLREGISTER_CHECKBASEINFO = 'SMALLREGISTER_CHECKBASEINFO' // 校验基本信息
export const SMALLREGISTER_SAVEALLINFO = 'SMALLREGISTER_SAVEALLINFO' // 保存小b企业注册信息
export const SMALLREGISTER_GETCOMPANYINFO = 'SMALLREGISTER_GETCOMPANYINFO' // 获取企业信息