export const REGISTERPROGRESS_GETIMGVERIFICATION = 'REGISTERPROGRESS_GETIMGVERIFICATION' // 获取图形验证码
export const REGISTERPROGRESS_GETMESSAGECODE = 'REGISTERPROGRESS_GETMESSAGECODE' // 获取短信验证码
export const REGISTERPROGRESS_GETSESSIONID = 'REGISTERPROGRESS_GETSESSIONID' // 获取sessionID（ 查询进度时入参）