export const GSAE_GETAPPLICATIONLIST = Symbol('GSAE_GETAPPLICATIONLIST')
export const GSAE_ADDAPPLICATIONINFO = Symbol('GSAE_ADDAPPLICATIONINFO')
export const GSAE_DELAPPLICATIONINFO = Symbol('GSAE_DELAPPLICATIONINFO')