/* 付款方账户list */
export const GETBATCHHANDLEPAYERLIST = 'GETBATCHHANDLEPAYERLIST'
/* 经办表单详情 */
export const UPDATEBATCHHANDLEORDERINFO = 'UPDATEBATCHHANDLEORDERINFO'
/* 业务规则list */
export const GETBATCHHANDLEBIZRULELIST = 'GETBATCHHANDLEBIZRULELIST'