/* 付款方账户list */
export const GETUNDERTAKESORGPAYERLIST = 'GETUNDERTAKESORGPAYERLIST'
/* 经办表单详情 */
export const UPDATEUNDERTAKESORGORDERINFO = 'UPDATEUNDERTAKESORGORDERINFO'
/* 业务规则list */
export const GETUNDERTAKESORGBIZRULELIST = 'GETUNDERTAKESORGBIZRULELIST'
/* 用途列表 */
export const GETUNDERTAKESORGPURPOSELIST = 'GETUNDERTAKESORGPURPOSELIST'