export const SENG_GETNOTIFICATIONLIST = 'SENG_GETNOTIFICATIONLIST'
export const SENG_UPDATESEARCHINFO = 'SENG_UPDATESEARCHINFO'
export const SENG_TYPEID = 'SENG_TYPEID'
export const SENG_GETLIST = 'SENG_GETLIST'
