export const DSCS_GETORDERLIST = Symbol('DSCS_GETORDERLIST')
export const DSCS_UPDATESEARCHINFO = Symbol('DSCS_UPDATESEARCHINFO')
export const DSCS_GETCOMPANYACCLIST = Symbol('DSCS_GETCOMPANYACCLIST')