export const SENA_GETNOTIFICATION = 'SENA_GETNOTIFICATION'
export const SENA_UPDATESEARCHINFO = 'SENA_UPDATESEARCHINFO'
export const SENA_GETINFO = 'SENA_GETINFO'
export const SENA_GETACCOUNTDATA = 'SENA_GETACCOUNTDATA'