export const GETBENEFICIARYEDITORLIST = Symbol('GETBENEFICIARYEDITORLIST')
export const BENEFICIARYEDITORSEARCH = Symbol('BENEFICIARYEDITORSEARCH')
export const CLEARBENEFICIARYEDITORSEARCH = Symbol('CLEARBENEFICIARYEDITORSEARCH')
export const DELBENEFICIARYEDITOR = Symbol('DELBENEFICIARYEDITOR')