export const SMSL_GETTABLELIST = 'SMSL_GETTABLELIST'
export const SMSL_GETTABLELISTS = 'SMSL_GETTABLELISTS'
export const SMSL_UPDATESEARCHINFO = 'SMSL_UPDATESEARCHINFO'
export const SMSL_SETCURRENTPAGEONE = 'SMSL_SETCURRENTPAGEONE'
